### ISSUE TITLE
Does not process Techguns Uranium

### ISSUE THREAD

**Issue by charliegc4** [phantamanta44/MekanismOres#14]
MekanismOres does not enable Mekanism to accept TechGuns Uranium in the Chemical Dissolution Chamber.

**Comment by phantamanta44** [comment]
so it turns out, techguns registered ore dictionary names incorrectly until [about a month ago](https://github.com/pWn3d1337/Techguns2/commit/8fbeed56a9c4633cf0e574a3d05bfe79e0494ac9), but they haven't actually pushed an update to curseforge for half a year. i made a change on the mekores end that'll fix it for now: https://www.curseforge.com/minecraft/mc-mods/mekanismores/files/2824322

**Comment by charliegc4** [comment]
Absolutely brilliant!

The other TechGuns ores I process first with an Oredictionificator anyway, so they are no problem, but now at last I can use the huge time and expense I invested in my tier 4 plant to process that Uranium. ;-)
